sonar.projectKey=secureops-app
sonar.projectName=SecureOps Platform
sonar.projectVersion=1.0.0
sonar.sources=app
sonar.language=py
sonar.python.version=3.12
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/tests/**
